name: Scrape Lightning Strikes

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:  # Manual trigger

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium matplotlib cartopy
          sudo apt-get update
          sudo apt-get install -y libgeos-dev  # For cartopy
      - name: Install Chrome and ChromeDriver
        run: |
          # Install prerequisites
          sudo apt-get update
          sudo apt-get install -y wget unzip

          # Download and install a specific Chrome version directly
          CHROME_VERSION="114.0.5735.90-1"  # Use a known stable version; adjust as needed
          wget -q "https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${CHROME_VERSION}_amd64.deb"
          sudo dpkg -i "google-chrome-stable_${CHROME_VERSION}_amd64.deb" || sudo apt-get install -f -y
          rm "google-chrome-stable_${CHROME_VERSION}_amd64.deb"

          # Verify Chrome version
          google-chrome --version

          # Install ChromeDriver for the matching version
          DRIVER_VERSION="114.0.5735.90"  # Match Chrome version
          wget -q "https://chromedriver.storage.googleapis.com/${DRIVER_VERSION}/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

          # Verify ChromeDriver version
          chromedriver --version
      - name: Run scraping script
        run: python scrape_and_plot.py
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add strikes.json worldwide_lightning_all_time.png
          git commit -m "Update strikes and PNG" || echo "No changes to commit"
          git push
