name: Scrape Lightning Strikes

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:  # Manual trigger

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium matplotlib cartopy
          sudo apt-get update
          sudo apt-get install -y libgeos-dev  # For cartopy
      - name: Install Chrome and ChromeDriver
        run: |
          # Install Chrome
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          
          # Get full Chrome version
          CHROME_FULL_VERSION=$(google-chrome --version | grep -oE "[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+")
          CHROME_MAJOR_VERSION=$(echo "$CHROME_FULL_VERSION" | cut -d'.' -f1)
          echo "Chrome full version: $CHROME_FULL_VERSION"
          echo "Chrome major version: $CHROME_MAJOR_VERSION"
          
          # Remove any existing ChromeDriver
          sudo rm -f /usr/local/bin/chromedriver
          
          # Try to fetch ChromeDriver for the major version from chrome-for-testing
          DRIVER_VERSION=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_${CHROME_MAJOR_VERSION}")
          echo "Attempted ChromeDriver version: $DRIVER_VERSION"
          
          if [ -z "$DRIVER_VERSION" ] || [ "$DRIVER_VERSION" = "404" ]; then
            echo "No ChromeDriver found for Chrome $CHROME_MAJOR_VERSION. Falling back to manual version selection."
            # Fallback: Try a known version close to 134.x (update this if needed)
            DRIVER_VERSION="134.0.6998.35"  # Hypothetical; adjust based on actual availability
          fi
          
          # Download and install ChromeDriver
          echo "Downloading ChromeDriver version: $DRIVER_VERSION"
          wget -q "https://storage.googleapis.com/chrome-for-testing-public/${DRIVER_VERSION}/linux64/chromedriver-linux64.zip" || {
            echo "Failed to download ChromeDriver $DRIVER_VERSION. Trying a fallback version."
            DRIVER_VERSION="133.0.6943.87"  # Known working version from your previous log
            wget -q "https://storage.googleapis.com/chrome-for-testing-public/${DRIVER_VERSION}/linux64/chromedriver-linux64.zip" || {
              echo "All download attempts failed."
              exit 1
            }
          }
          
          unzip chromedriver-linux64.zip
          if [ -f chromedriver-linux64/chromedriver ]; then
            sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
          else
            sudo mv chromedriver /usr/local/bin/
          fi
          sudo chmod +x /usr/local/bin/chromedriver
          
          # Verify installation
          INSTALLED_DRIVER_VERSION=$(chromedriver --version | grep -oE "[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+")
          echo "Installed ChromeDriver version: $INSTALLED_DRIVER_VERSION"
          
          # Check version compatibility (warn but don’t fail)
          if ! echo "$INSTALLED_DRIVER_VERSION" | grep -q "^${CHROME_MAJOR_VERSION}"; then
            echo "Warning: ChromeDriver version ($INSTALLED_DRIVER_VERSION) does not match Chrome major version ($CHROME_MAJOR_VERSION). This might cause issues."
          else
            echo "ChromeDriver version matches Chrome major version."
          fi
      - name: Run scraping script
        run: python scrape_and_plot.py
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add strikes.json australia_lightning_24h.png
          git commit -m "Update strikes and PNG" || echo "No changes to commit"
          git push
