name: Scrape Lightning Strikes

on:
  schedule:
    - cron: '*/6 * * * *'  # Every 6 minutes
  workflow_dispatch:  # Manual trigger

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium matplotlib cartopy
          sudo apt-get update
          sudo apt-get install -y libgeos-dev  # For cartopy
      - name: Install Chrome and ChromeDriver
        run: |
          # Install Chrome
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          
          # Get Chrome version
          CHROME_VERSION=$(google-chrome --version | grep -oE "[0-9]+\.[0-9]+\.[0-9]+")
          echo "Chrome version: $CHROME_VERSION"
          
          # Remove any existing ChromeDriver to avoid conflicts
          sudo rm -f /usr/local/bin/chromedriver
          
          # Fetch the latest ChromeDriver version for this Chrome major version
          DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}")
          if echo "$DRIVER_VERSION" | grep -q "<Error>"; then
            echo "No exact match for Chrome $CHROME_VERSION. Checking available releases..."
            ALL_VERSIONS=$(curl -s "https://chromedriver.storage.googleapis.com/?delimiter=/&prefix=" | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+' | sort -V)
            echo "Available versions: $ALL_VERSIONS"
            DRIVER_VERSION=$(echo "$ALL_VERSIONS" | grep "^${CHROME_VERSION}" | tail -n 1)
            if [ -z "$DRIVER_VERSION" ]; then
              echo "No matching $CHROME_VERSION.x version found. Using hardcoded fallback for Chrome 133.x."
              DRIVER_VERSION="133.0.6943.106"  # Known compatible version for Chrome 133.x
            fi
          fi
          if [ -z "$DRIVER_VERSION" ]; then
            echo "Error: Could not determine a valid ChromeDriver version. Using hardcoded fallback."
            DRIVER_VERSION="133.0.6943.106"
          fi
          echo "Using ChromeDriver version: $DRIVER_VERSION"
          
          # Download and install ChromeDriver with verbose output
          wget -v "https://chromedriver.storage.googleapis.com/${DRIVER_VERSION}/chromedriver_linux64.zip" || { echo "Failed to download ChromeDriver version $DRIVER_VERSION"; exit 1; }
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          
          # Verify installation matches Chrome version
          INSTALLED_DRIVER_VERSION=$(chromedriver --version | grep -oE "[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+")
          echo "Installed ChromeDriver version: $INSTALLED_DRIVER_VERSION"
          if ! echo "$INSTALLED_DRIVER_VERSION" | grep -q "^${CHROME_VERSION}"; then
            echo "Error: ChromeDriver version ($INSTALLED_DRIVER_VERSION) does not match Chrome version ($CHROME_VERSION)"
            exit 1
          fi
      - name: Run scraping script
        run: python scrape_and_plot.py
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add strikes.json australia_lightning_24h.png
          git commit -m "Update strikes and PNG" || echo "No changes to commit"
          git push
