name: Scrape Lightning Strikes

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:  # Manual trigger

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium matplotlib cartopy
          sudo apt-get update
          sudo apt-get install -y libgeos-dev  # For cartopy
      - name: Install Chrome and ChromeDriver
        run: |
          # Install Chrome
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          
          # Get Chrome version
          FULL_CHROME_VERSION=$(google-chrome --version | grep -oE "[0-9]+\.[0-9]+\.[0-9]+")
          CHROME_MAJOR_VERSION=$(echo "$FULL_CHROME_VERSION" | cut -d'.' -f1)
          echo "Full Chrome version: $FULL_CHROME_VERSION"
          echo "Chrome major version: $CHROME_MAJOR_VERSION"
          
          # Aggressive cleanup of any existing ChromeDriver
          sudo find / -name "chromedriver" -exec rm -f {} \; 2>/dev/null || echo "No unexpected chromedriver found"
          rm -rf chromedriver chromedriver-linux64 chromedriver-linux64.zip
          echo "Cleared all potential ChromeDriver files."
          
          # Set ChromeDriver version
          DRIVER_VERSION="134.0.6998.35"
          echo "Selected ChromeDriver version: $DRIVER_VERSION"
          
          # Download ChromeDriver
          DOWNLOAD_URL="https://storage.googleapis.com/chrome-for-testing-public/${DRIVER_VERSION}/linux64/chromedriver-linux64.zip"
          echo "Downloading from: $DOWNLOAD_URL"
          wget -v "$DOWNLOAD_URL" -O chromedriver-linux64.zip || {
            echo "Error: Failed to download ChromeDriver $DRIVER_VERSION."
            exit 1
          }
          
          # Verify download
          ls -lh chromedriver-linux64.zip
          echo "Downloaded file size: $(stat -c %s chromedriver-linux64.zip) bytes"
          
          # Unzip and verify
          unzip -o chromedriver-linux64.zip
          ls -lh chromedriver-linux64/chromedriver
          ./chromedriver-linux64/chromedriver --version
          EXPECTED_VERSION="134.0.6998.35"
          if ! ./chromedriver-linux64/chromedriver --version | grep -q "$EXPECTED_VERSION"; then
            echo "Error: Downloaded ChromeDriver version does not match expected $EXPECTED_VERSION"
            exit 1
          fi
          echo "Verified downloaded ChromeDriver is $EXPECTED_VERSION"
          
          # Install to a unique path and update PATH
          sudo mkdir -p /opt/chromedriver
          sudo mv chromedriver-linux64/chromedriver /opt/chromedriver/chromedriver
          sudo chmod +x /opt/chromedriver/chromedriver
          echo "/opt/chromedriver" | sudo tee -a /etc/environment
          export PATH="/opt/chromedriver:$PATH"
          
          # Verify installed version
          which chromedriver
          INSTALLED_DRIVER_VERSION=$(chromedriver --version | grep -oE "[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+")
          echo "Installed ChromeDriver version: $INSTALLED_DRIVER_VERSION"
          if ! echo "$INSTALLED_DRIVER_VERSION" | grep -q "^${CHROME_MAJOR_VERSION}"; then
            echo "Error: Installed ChromeDriver version ($INSTALLED_DRIVER_VERSION) does not match Chrome major version ($CHROME_MAJOR_VERSION)"
            exit 1
          fi
          echo "Chrome and ChromeDriver versions are compatible."
      - name: Run scraping script
        run: python scrape_and_plot.py
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add strikes.json australia_lightning_24h.png
          git commit -m "Update strikes and PNG" || echo "No changes to commit"
          git push
